@extends('layouts.app')
@section('title','拍卖会所')
@section('content')
<h4>拍卖会所 · Auction</h4><p>Listing fee: 500 Gold · 30 seconds between listings · Last-minute bids extend the deadline to 15 minutes · Auctions cannot be cancelled</p>
@if(!$members)<form method="post" action="{{ route('auction.join') }}">@csrf<input type="hidden" name="operation_id" value="{{ (string) Str::uuid() }}"><button>购买会员卡 · 11,000 Gold</button></form>@endif
<p><a href="?sort=time">结束时间</a> · <a href="?sort=price">价格 ↓</a> · <a href="?sort=rprice">价格 ↑</a> · <a href="?sort=bid">出价次数</a> · <a href="?mine=1">我的拍卖</a> · <a href="{{ route('auction') }}">全部</a></p>
<div class="table-scroll"><table><tr><th>No.</th><th>Item</th><th>价格</th><th>投标人 / 参展人</th><th>结束 (UTC)</th><th>Bid</th></tr>
@forelse($listings as $listing)<tr><td>{{ $listing->id }}</td><td>{{ $catalog->get('items',$listing->item_snapshot['item_id'])['name'] }} +{{ $listing->item_snapshot['refinement'] }} ×{{ $listing->item_snapshot['quantity'] }}<br>{{ $listing->comment }}</td><td>{{ number_format($listing->price) }} ({{ $listing->bid_count }})</td><td>{{ $names[$listing->bidder_id] ?? '—' }} / {{ $names[$listing->seller_id] ?? '—' }}</td><td>{{ $listing->ends_at }}</td><td>@if($members)<form method="post" action="{{ route('auction.bid',$listing->id) }}">@csrf<input type="hidden" name="operation_id" value="{{ (string) Str::uuid() }}"><input aria-label="Bid amount" type="number" name="price" min="{{ \App\Application\Multiplayer\AuctionService::minimumBid($listing->price) }}" value="{{ \App\Application\Multiplayer\AuctionService::minimumBid($listing->price) }}" required><button>出价</button></form>@endif</td></tr>@empty<tr><td colspan="6">无拍卖物 · No active auctions</td></tr>@endforelse</table></div>
@if($members)<h4>拍卖物品 · List an item</h4><form method="post" action="{{ route('auction.exhibit') }}">@csrf<input type="hidden" name="operation_id" value="{{ (string) Str::uuid() }}"><label>物品 <select name="inventory_id" required>@foreach($items as $item)@if(in_array($catalog->get('items',$item->item_id)['type']??'',\App\Application\Multiplayer\AuctionService::TYPES,true))<option value="{{ $item->id }}">{{ $catalog->get('items',$item->item_id)['name'] }} +{{ $item->refinement }} ×{{ $item->quantity }}</option>@endif @endforeach</select></label><label>数量 <input type="number" name="quantity" min="1" value="1" required></label><label>起始价格 <input type="number" name="price" min="0" value="0" required></label><label>小时 <select name="hours">@foreach([1,3,6,12,18,24] as $hours)<option>{{ $hours }}</option>@endforeach</select></label><label>描述 <input name="comment" maxlength="200"></label><button>上架 · 500 Gold</button></form>@endif
<h4>拍卖记录 · History</h4><ul>@foreach($events as $event)<li>{{ $event->created_at }} · #{{ $event->auction_listing_id }} · {{ $event->kind }} · {{ $names[$event->user_id] ?? '—' }} · {{ number_format($event->amount) }}</li>@endforeach</ul>
@endsection
